# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc_package import callinvoker_pb2 as callinvoker__pb2


class CallInvokerStub(object):
    """define a service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call = channel.unary_unary(
                '/rpc_package.CallInvoker/call',
                request_serializer=callinvoker__pb2.CallRequest.SerializeToString,
                response_deserializer=callinvoker__pb2.CallResponse.FromString,
                )


class CallInvokerServicer(object):
    """define a service
    """

    def call(self, request, context):
        """define the interface and data type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CallInvokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call': grpc.unary_unary_rpc_method_handler(
                    servicer.call,
                    request_deserializer=callinvoker__pb2.CallRequest.FromString,
                    response_serializer=callinvoker__pb2.CallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_package.CallInvoker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CallInvoker(object):
    """define a service
    """

    @staticmethod
    def call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc_package.CallInvoker/call',
            callinvoker__pb2.CallRequest.SerializeToString,
            callinvoker__pb2.CallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
